version: 2.1
orbs:
  ruby: circleci/ruby@1.1.3
  heroku: circleci/heroku@1.2.3

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.5
    working_directory: ~/qr-meal-app/qr-meal_api
    steps:
      - checkout:
          path: ~/qr-meal-app
      - ruby/install-deps

  test:
    docker:
      - image: cimg/ruby:3.2.5
      - image: cimg/postgres:13.4
        environment:
          POSTGRES_ROOT_PASSWORD: password
          POSTGRES_DATABASE: qr_meal_api_test
          POSTGRES_USER: user
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/qr-meal-app/qr-meal_api
    steps:
      - checkout:
          path: ~/qr-meal-app
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: test
          command: bundle exec rake test

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
