version: 2.1
orbs:
  ruby: circleci/ruby@1.1.3
  heroku: circleci/heroku@1.2.3

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.5
    working_directory: ~/qr-meal-app/qr-meal_api
    steps:
      - checkout:
          path: ~/qr-meal-app
      - run:
          name: Set Bundler Configuration
          command: |
            bundle config set path './vendor/bundle'
            bundle config set deployment 'true'
      - run:
          name: Install Specific Bundler Version
          command: gem install bundler -v 2.5.21
      - ruby/install-deps

  test:
    docker:
      - image: cimg/ruby:3.2.5
      - image: cimg/postgres:13.4
        environment:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: qr_meal_api_test
          POSTGRES_USER: user
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/qr-meal-app/qr-meal_api
    steps:
      - checkout:
          path: ~/qr-meal-app
      - run:
          name: Set Bundler Configuration
          command: |
            bundle config set path './vendor/bundle'
            bundle config set deployment 'true'
       - run:
          name: Install Specific Bundler Version
          command: gem install bundler -v 2.5.21
      - ruby/install-deps
      - run:
        name: Wait for PostgreSQL to be ready
        command: |
          for i in `seq 1 10`; do
            nc -zv 127.0.0.1 5432 && exit 0
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
          echo "PostgreSQL is not available yet" && exit 1
      - run:
          name: Create Test Database
          command: bundle exec rails db:create
      - run:
          name: Migrate Database
          command: bundle exec rails db:migrate
      - run:
          name: Run Tests
          command: bundle exec rake test

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
